---

basepath: "/var/www/html/repos"

repos:
  repo-zabbix7:
    name: "zabbix2.2"
    url: "http://repo.zabbix.com/zabbix/2.2/rhel/7/x86_64"
    arch: "x86_64"
    osver: "centos7"
    stable_release: "20150407"
    link_type: hardlink
    delete: true
  repo-zabbix6:
    name: "zabbix2.2"
    url: "http://repo.zabbix.com/zabbix/2.2/rhel/6/x86_64"
    arch: "x86_64"
    osver: "centos6"
    stable_release: "20150407"
    link_type: hardlink
    delete: true
  repo-newrelic5:
    name: "newrelic"
    url: "http://yum.newrelic.com/pub/newrelic/el5/x86_64"
    arch: "x86_64"
    osver: "centos5"
    stable_release: "20150407"
    link_type: hardlink
    delete: true
  repo-newrelic6:
    name: "newrelic"
    url: "http://yum.newrelic.com/pub/newrelic/el5/x86_64"
    arch: "x86_64"
    osver: "centos6"
    stable_release: "20150408"
    link_type: hardlink
    delete: true
  repo-ppl-prod5:
    name: "puppetlabs-prod"
    url: "https://yum.puppetlabs.com/el/5/products/x86_64"
    arch: "x86_64"
    osver: "centos5"
    stable_release: "20150422"
    link_type: hardlink
    delete: true
  repo-ppl-deps5:
    name: "puppetlabs-dep"
    url: "https://yum.puppetlabs.com/el/5/dependencies/x86_64"
    arch: "x86_64"
    osver: "centos5"
    stable_release: "20150422"
    link_type: hardlink
    delete: true
  repo-ppl-prod6:
    name: "puppetlabs-prod"
    url: "https://yum.puppetlabs.com/el/6/products/x86_64"
    arch: "x86_64"
    osver: "centos6"
    stable_release: "20150407"
    link_type: hardlink
    delete: true
  repo-ppl-deps6:
    name: "puppetlabs-dep"
    url: "https://yum.puppetlabs.com/el/6.5/dependencies/x86_64"
    arch: "x86_64"
    osver: "centos6"
    stable_release: "20150407"
    link_type: hardlink
    delete: true
  repo-centos5.8-base-64:
    name: "centos-base"
    url: "http://vault.centos.org/5.8/os/x86_64"
    arch: "x86_64"
    osver: "centos5.8"
    stable_release: "20150422"
    link_type: hardlink
    delete: true
  repo-centos5.8-updates-64:
    name: "centos-updates"
    url: "http://vault.centos.org/5.8/updates/x86_64"
    arch: "x86_64"
    osver: "centos5.8"
    stable_release: "20150422"
    link_type: hardlink
    delete: true
  repo-centos5-latest-base-64:
    name: "centos-base"
    url: "http://www.mirrorservice.org/sites/mirror.centos.org/5/os/x86_64"
    arch: "x86_64"
    osver: "centos5"
    stable_release: "20150422"
    link_type: hardlink
    delete: true
  repo-centos5-latest-updates-64:
    name: "centos-updates"
    url:  "http://www.mirrorservice.org/sites/mirror.centos.org/5/updates/x86_64"
    arch: "x86_64"
    osver: "centos5"
    stable_release: "20150422"
    link_type: hardlink
    delete: true
  repo-centos6.6-base-64:
    name: "centos-base"
    url: "http://www.mirrorservice.org/sites/mirror.centos.org/6.6/os/x86_64"
    arch: "x86_64"
    osver: "centos6.6"
    stable_release: "20150408"
    link_type: hardlink
    delete: true
  repo-centos6.6-updates-64:
    name: "centos-updates"
    url: "http://www.mirrorservice.org/sites/mirror.centos.org/6.6/updates/x86_64"
    arch: "x86_64"
    osver: "centos6.6"
    stable_release: "20150408"
    link_type: hardlink
    delete: true
  repo-centos6.6-plus-64:
    name: "centos-plus"
    url: "http://www.mirrorservice.org/sites/mirror.centos.org/6.6/centosplus/x86_64"
    arch: "x86_64"
    osver: "centos6.6"
    stable_release: "20150408"
    link_type: hardlink
    delete: true
  repo-centos6.6-extras-64:
    name: "centos-extras"
    url: "http://www.mirrorservice.org/sites/mirror.centos.org/6.6/extras/x86_64/"
    arch: "x86_64"
    osver: "centos6.6"
    stable_release: "20150408"
    link_type: hardlink
    delete: true
  repo-centos7.1-base-64:
    name: "centos-base"
    url: "http://www.mirrorservice.org/sites/mirror.centos.org/7.1.1503/os/x86_64"
    arch: "x86_64"
    osver: "centos7.1"
    stable_release: "20150413"
    link_type: hardlink
    delete: true
  repo-centos7.1-updates-64:
    name: "centos-updates"
    url: "http://www.mirrorservice.org/sites/mirror.centos.org/7.1.1503/updates/x86_64"
    arch: "x86_64"
    osver: "centos7.1"
    stable_release: "20150408"
    link_type: hardlink
    delete: true
  repo-centos7.1-plus-64:
    name: "centos-plus"
    url: "http://www.mirrorservice.org/sites/mirror.centos.org/7.1.1503/centosplus/x86_64"
    arch: "x86_64"
    osver: "centos7.1"
    stable_release: "20150408"
    link_type: hardlink
    delete: true
  repo-centos7.1-extras-64:
    name: "centos-extras"
    url: "http://www.mirrorservice.org/sites/mirror.centos.org/7.1.1503/extras/x86_64/"
    arch: "x86_64"
    osver: "centos7.1"
    stable_release: "20150408"
    link_type: hardlink
    delete: true
  repo-epel-el6-x86_64:
    name: "epel"
    url: "http://dl.fedoraproject.org/pub/epel/6/x86_64"
    arch: "x86_64"
    osver: "centos6"
    stable_release: "20150408"
    link_type: hardlink
    delete: true
  repo-epel-el7-x86_64:
    name: "epel"
    url: "http://dl.fedoraproject.org/pub/epel/7/x86_64"
    arch: "x86_64"
    osver: "centos7"
    stable_release: "20150610"
    link_type: hardlink
    delete: true
  repo-vmware-tools-55:
    name: "vmware-tools55"
    url: "http://packages.vmware.com/tools/esx/5.5/rhel6/x86_64"
    arch: "x86_64"
    osver: "centos6"
    stable_release: "20150413"
    link_type: hardlink
    delete: true
  repo-dag-rpmforge-Centos5-x86-64:
    name: "rpmforge"
    url: "http://www.mirrorservice.org/sites/apt.sw.be/redhat/el5/en/x86_64/rpmforge"
    arch: "x86_64"
    osver: "centos5"
    stable_release: "20150422"
    link_type: hardlink
    delete: true
  repo-ppl-pc1-prod7-x86-64:
    name: "puppet-labs-pc1"
    url: "http://yum.puppetlabs.com/el/7/PC1/x86_64"
    arch: "x86_64"
    osver: "centos7"
    stable_release: "20150519"
    link_type: hardlink
    delete: true
  repo-percona-Centos7-x86-64:
    name: "percona"
    url: "http://repo.percona.com/centos/7/RPMS/x86_64"
    arch: "x86_64"
    osver: "centos7"
    stable_release: "20150619"
    link_type: hardlink
    delete: true
  repo-local-test-Centos62-x86-64:
    name: "local_test"
    arch: "x86_64"
    osver: "centos6"
    stable_release: "20150817"
    repo_type: "local"
    link_type: symlink
    delete: false
  repo-local-test-Centos7-x86-64:
    name: "local_test"
    arch: "x86_64"
    osver: "centos7"
    stable_release: "20150817"
    repo_type: "local"
    link_type: symlink
    delete: false
